[package]
name = "calc-core-wasm"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
calc-core-rust = { path = "../calc-core-rust" }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "0.2"
